// WARNING: DO NOT EDIT THIS FILE, IT IS AUTOGENERATED
/** @type {import("c3ide2-types").Plugin} */
const Config = {
    addonType: "plugin",
    id: "mikal_steamworks_for_js",
    name: "Steamworks for js",
    version: "1.0.0",
    category:
        // "3d",
        // "data-and-storage",
        // "form-controls",
        // "input",
        // "media",
        // "monetisation",
        // "platform-specific",
        // "web",
        // "other"
        "general",
    author: "Mikal",
    website: "https://www.construct.net",
    documentation: "https://www.construct.net",
    description: "Description",
    // addonUrl: "https://www.construct.net/en/make-games/addons/####/XXXX", // displayed in auto-generated docs
    // githubUrl: "https://github.com/skymen/XXXX", // displays latest release version in auto-generated docs
    // icon: "icon.svg", // defaults to "icon.svg" if omitted
    type: "object", // world, object, dom
    domSideScripts: ["steamworks.js"],
    /* extensionScript: {
    enabled: false, // set to false to disable the extension script
    watch: false, // set to true to enable live reload on changes during development
    targets: [
      "x86",
      "x64",
      // "ARM64", // Disabled for now because the provided base project doesn't support it
    ],

    // you don't need to change this, the build step will rename the dll for you. Only change this if you change the name of the dll exported by Visual Studio
    name: "MyExtension",
  }, */
    fileDependencies: [
        /*
    {
      filename: "filename.js", // no need to include "c3runtime/" prefix
      type:
        "copy-to-output"
        "inline-script"
        "external-dom-script"
        "external-runtime-script"
        "external-css"

      // for copy-to-output only
      // fileType: "image/png"
    }
    */
        /*
        {
            filename: "steamworks.js", // no need to include "c3runtime/" prefix
            type: "external-dom-script",
        },
    */
        {
            filename: "steamworksjs.win32-x64-msvc.node", // no need to include "c3runtime/" prefix
            type: "copy-to-output",
            fileType: "application/octet-stream",
        },
        {
            filename: "steamworksjs.darwin-x64.node", // no need to include "c3runtime/" prefix
            type: "copy-to-output",
            fileType: "application/octet-stream",
        },
        {
            filename: "libsteam_api.dylib", // no need to include "c3runtime/" prefix
            type: "copy-to-output",
            fileType: "application/octet-stream",
        },
        {
            filename: "steam_api64.dll", // no need to include "c3runtime/" prefix
            type: "copy-to-output",
            fileType: "application/octet-stream",
        },
        /*        {
            filename: "steamworksjs.linux-x64-gnu.node", // no need to include "c3runtime/" prefix
            type: "copy-to-output",
        },
        {
            filename: "steamworksjs.darwin-x64.node", // no need to include "c3runtime/" prefix
            type: "copy-to-output",
        },
        {
            filename: "steamworksjs.darwin-arm64.node", // no need to include "c3runtime/" prefix
            type: "copy-to-output",
        },
        */
    ],
    info: {
        // world only
        defaultImageUrl: null,
        Set: {
            // world only
            IsResizable: false,
            IsRotatable: false,
            Is3D: false,
            HasImage: false,
            IsTiled: false,
            SupportsZElevation: false,
            SupportsColor: false,
            SupportsEffects: false,
            MustPreDraw: false,

            // object only
            IsSingleGlobal: true,

            // world and object
            CanBeBundled: false,
            IsDeprecated: false,
            GooglePlayServicesEnabled: false,
        },
        AddCommonACEs: {
            // world only
            Position: false,
            SceneGraph: false,
            Size: false,
            Angle: false,
            Appearance: false,
            ZOrder: false,
        },
    },
    properties: [
        /*
    {
      type:
        "integer"
        "float"
        "percent"
        "text"
        "longtext"
        "check"
        "font"
        "combo"
        "color"
        "object"
        "group"
        "link"
        "info"

      id: "property_id",
      options: {
        initialValue: 0,
        interpolatable: false,

        // minValue: 0, // omit to disable
        // maxValue: 100, // omit to disable

        // for type combo only
        // items: [
        //   {itemId1: "item name1" },
        //   {itemId2: "item name2" },
        // ],

        // dragSpeedMultiplier: 1, // omit to disable

        // for type object only
        // allowedPluginIds: ["Sprite", "<world>"],

        // for type link only
        // linkCallback: `function(instOrObj) {}`,
        // linkText: "Link Text",
        // callbackType:
        //   "for-each-instance"
        //   "once-for-type"

        // for type info only
        // infoCallback: `function(inst) {}`,
      },
      name: "Property Name",
      desc: "Property Description",
    }
    */
        {
            type: "integer",
            options: {
                initialValue: 480,
                interpolatable: false,
            },
            name: "Steam App Id",
            desc: "Steam App Id, 480 is a steam test id",
        },
    ],
    aceCategories: {
        general: "General",
    },
    Acts: {
        /*
    SampleAction: {
      // The category of the action as it appears in the add action dialog
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this action
      // Cases where you might not want this are:
      // 1- If the action params are incompatible with the script interface
      // 2- If you don't want it to appear in the script interface
      // 3- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the action in the add action dialog
      highlight: true,

      // Set to true to hide the action in the interface. False by default if not specified.
      deprecated: false,

      // Marks the action as async. Defaults to false if not specified.
      isAsync: false,

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
            - "boolean"

            // The following types can take a default value but CANNOT be automatically generated in the script interface
            - "combo"

            // The following types CANNOT take a default value AND CANNOT be automatically generated in the script interface
            - "cmp"
            - "object"
            - "objectname"
            - "layer"
            - "layout"
            - "keyb"
            - "instancevar"
            - "instancevarbool"
            - "eventvar"
            - "eventvarbool"
            - "animation"
            - "objinstancevar"

          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          initialValue: "the default value of the parameter",

          // Only for type "combo"
          items: [
            {"itemId1": "itemName1"},
            {"itemId2": "itemName2"},
            {"itemId3": "itemName3"},
          ],

          // Only for type "object"
          allowedPluginIds: ["Sprite", "TiledBg"],
        },
      ],

      // The name of the action as it appears in the add action dialog
      listName: "Sample Action",

      // The text that appears in the event sheet. Note, every single param must be used in the display text.
      // You can also use [b] and [i] tags.
      displayText: "Sample action [i]{0}[/i]",

      // The description of the action as it appears in the add action dialog
      description: "This is a sample action",
    },
    */
        Initialize: {
            // The category of the action as it appears in the add action dialog
            category: "general",
            forward: "_Initialize",
            autoScriptInterface: true,
            highlight: true,
            deprecated: false,
            isAsync: true,

            // list of parameters
            params: [
                {
                    id: "appId",
                    name: "Application Id",
                    desc: "Steam application id",
                    type: "number",
                    initialValue: 0,
                },
            ],

            // The name of the action as it appears in the add action dialog
            listName: "Initialize Steamworks",

            // The text that appears in the event sheet. Note, every single param must be used in the display text.
            // You can also use [b] and [i] tags.
            displayText: "Initialize Steamworks, app id [i]{0}[/i]",

            // The description of the action as it appears in the add action dialog
            description: "Initialize Steamworks",
        },

        SetAchievement: {
            // The category of the action as it appears in the add action dialog
            category: "general",
            forward: "_SetAchievement",
            autoScriptInterface: true,
            highlight: true,
            deprecated: false,
            isAsync: true,

            // list of parameters
            params: [
                {
                    id: "achievementId",
                    name: "Achievement Id",
                    desc: "Steam achievement id",
                    type: "string",
                    initialValue: "",
                },
            ],

            // The name of the action as it appears in the add action dialog
            listName: "Set Achievement",

            // The text that appears in the event sheet. Note, every single param must be used in the display text.
            // You can also use [b] and [i] tags.
            displayText: "Set achievement [i]{0}[/i]",

            // The description of the action as it appears in the add action dialog
            description: "Set achievement",
        },
    },
    Cnds: {
        /*
    SampleCondition: {
      // The category of the action as it appears in the add condition dialog
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this condition
      // Cases where you might not want this are:
      // 1- If the condition params are incompatible with the script interface
      // 2- If you don't want it to appear in the script interface
      // 3- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the condition in the add condition dialog
      highlight: true,

      // Set to true to hide the condition in the interface. False by default if not specified.
      deprecated: false,

      // special conditions properties. These can all be omitted, and they will default to the following values:
      isTrigger: false,
      isFakeTrigger: false,
      isStatic: false,
      isLooping: false,
      isInvertible: true,
      isCompatibleWithTriggers: true,

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
            - "boolean"

            // The following types can take a default value but CANNOT be automatically generated in the script interface
            - "combo"

            // The following types CANNOT take a default value AND CANNOT be automatically generated in the script interface
            - "cmp"
            - "object"
            - "objectname"
            - "layer"
            - "layout"
            - "keyb"
            - "instancevar"
            - "instancevarbool"
            - "eventvar"
            - "eventvarbool"
            - "animation"
            - "objinstancevar"

          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          initialValue: "the default value of the parameter",

          // Only for type "combo"
          items: [
            {"itemId1": "itemName1"},
            {"itemId2": "itemName2"},
            {"itemId3": "itemName3"},
          ],

          // Only for type "object"
          allowedPluginIds: ["Sprite", "TiledBg"],
        },
      ],

      // The name of the condition as it appears in the add condition dialog
      listName: "Sample Condition",

      // The text that appears in the event sheet. Note, every single param must be used in the display text.
      // You can also use [b] and [i] tags.
      displayText: "Sample condition [i]{0}[/i]",

      // The description of the condition as it appears in the add condition dialog
      description: "This is a sample condition",
    },
    */
    },
    Exps: {
        /*
    SampleExpression: {
      // The category of the action as it appears in the expression picker
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this expression
      // Cases where you might not want this are:
      // 1- If you don't want it to appear in the script interface
      // 2- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the expression in the expression picker
      highlight: true,

      // Set to true to hide the expression in the interface. False by default if not specified.
      deprecated: false,

      // The type of the expression.
      returnType:
        - "string"
        - "number"
        - "any" // must be either string or number

      // Set to true if the expression is variadic. False by default if not specified.
      isVariadicParameters: false

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
        },
      ],

      // The description of the expression as it appears in the expression picker
      description: "This is a sample expression",
    },
    */
    },
};

module.exports = Config;
